package com.bincai.cloud.cust.domain.dao;

import java.util.List;

import com.bincai.cloud.cust.domain.model.Customer;

public interface CustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cu_customer
     *
     * @mbggenerated Thu Sep 08 13:34:57 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cu_customer
     *
     * @mbggenerated Thu Sep 08 13:34:57 CST 2016
     */
    int insert(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cu_customer
     *
     * @mbggenerated Thu Sep 08 13:34:57 CST 2016
     */
    int insertSelective(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cu_customer
     *
     * @mbggenerated Thu Sep 08 13:34:57 CST 2016
     */
    Customer selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cu_customer
     *
     * @mbggenerated Thu Sep 08 13:34:57 CST 2016
     */
    int updateByPrimaryKeySelective(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cu_customer
     *
     * @mbggenerated Thu Sep 08 13:34:57 CST 2016
     */
    int updateByPrimaryKey(Customer record);
    
    List<Customer> selectByCondition(Customer record);
    
    int searchCount(Customer record);
    
    Customer selectById(String Id);
    
    
    int delete(String id);
}